14:02:38.113 INFO Test execution started: second_test
14:02:38.114 INFO Browser: chrome
14:02:38.114 INFO Environment: test_env
14:02:38.114 INFO Using data:
    order_type: Plats
    document_type: CORRECTION OF PLAT (PL)
    num_of_pages: 1
    num_of_lots: 1
    section: GRANTOR
    first_name: First Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
14:02:41.369 INFO Navigate to: 'http://User1:Automation_1_3@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer='
14:02:52.489 INFO Click addNewOrderButton
14:02:58.172 INFO Waiting for 3 seconds
14:03:01.198 INFO Click orderTypeDropdown
14:03:01.335 INFO Click //select[@id='orderTypeId']/option[text()='Plats']
14:03:04.253 INFO Click documentTypeDropdown
14:03:04.349 INFO Click //select[@id='Order_OrderItems[0]_Document_DocumentTypeId']/option[text()='CORRECTION OF PLAT (PL)']
14:03:04.414 INFO Write '1' in element numberOfPages
14:03:04.507 INFO Write '1' in element numberOfLots
14:03:04.602 INFO Click partiesTab
14:03:04.711 INFO Write 'asd' in element //input[@placeholder='First Name']
14:03:04.915 ERROR AttributeError: module 'golem.actions' has no attribute 'driver'
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 24, in test
    a.driver.set_window_position(0,0)
AttributeError: module 'golem.actions' has no attribute 'driver'

14:03:07.569 INFO Test Result: CODE ERROR
