12:58:52.916 INFO Test execution started: second_test
12:58:52.916 INFO Browser: chrome-remote
12:58:52.916 INFO Environment: test_env
12:58:52.917 INFO Using data:
    order_type: Plats
    document_type: CORRECTION OF PLAT (PL)
    num_of_pages: 1
    num_of_lots: 1
    section: GRANTOR
    first_name: First Name
    alert_text: Please Enter Account OR Email OR Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
12:58:53.546 ERROR NameError: name 'dumps' is not defined
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 34, in test
    f.write(json,dumps(to_json))
NameError: name 'dumps' is not defined

12:58:53.720 INFO Test Result: CODE ERROR
