11:44:35.527 INFO Test execution started: second_test
11:44:35.528 INFO Browser: chrome-remote
11:44:35.528 INFO Environment: test_env
11:44:35.528 INFO Using data:
    order_type: Plats
    document_type: CORRECTION OF PLAT (PL)
    num_of_pages: 1
    num_of_lots: 1
    section: GRANTOR
    first_name: First Name
    alert_text: Please Enter Account OR Email OR Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
11:44:36.216 ERROR UnsupportedOperation: not writable
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 32, in test
    json.dump(data, file)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
io.UnsupportedOperation: not writable

11:44:36.387 INFO Test Result: CODE ERROR
